M48
; DRILL file {KiCad 6.0.11+dfsg-1} date Sat 22 Mar 2025 08:52:34 PM CET
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-22T20:52:34+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.11+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.250
%
G90
G05
T1
X103.5Y-47.5
X103.5Y-96.5
X161.5Y-47.5
X161.5Y-96.5
T2
X112.085Y-91.82
X123.515Y-91.82
X140.485Y-91.82
X151.915Y-91.82
T0
M30
